Lint/DuplicateCaseCondition:
  Exclude:
    - 'spec/chef/knife/linode_server_create_spec.rb'

Lint/EmptyWhen:
  Exclude:
    - 'spec/chef/knife/linode_server_create_spec.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/chef/knife/linode_base.rb'
    - 'lib/chef/knife/linode_stackscript_list.rb'
