Style/Documentation:
  Enabled: false

Style/MethodLength:
  Enabled: false
#  Max: 40

Style/ClassLength:
  Max: 250

Style/LineLength:
  Enabled: false

Style/CyclomaticComplexity:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/ClassVars:
  Enabled: false
